title = "Sandy's Website ğŸš€"
url = "https://sandyuraz.com"

[website]
locale = "en_GB"
color = "#fffff4"
twitter = "@sandyuraz"
styles = ["css/web.css"]
tombs = ["blogs", "anime", "arts"]
exclude = ["present"]

[author]
image = "najimi.webp"
name = "sandy"
email = "[at] sandyuraz [dot] com"

[navigation]

[navigation.1]
link = "dossier"
title = "Dossier ğŸ–‹"

[navigation.2]
link = "books"
title = "Bookshelf ğŸ“–"

[navigation.3]
link = "fortunes"
title = "Fortunes ğŸ¥ "

[navigation.4]
link = ""
title = "Home ğŸ "
