title = "Sandyâ€™s Website â›©ï¸"
url = "https://sandyuraz.com"

[website]
locale = "en_GB"
color = "#fffff4"
twitter = "@sandyuraz"
styles = ["css/web.css"]
tombs = ["blogs", "anime", "arts"]
preview = "preview.jpg"
description_length = 137
normalize_headings = false
roman_footnotes = true
footnote_brackets = false
holoscene_dates = true

syntax_highlighting = true
syntax_highlighting_theme = "scripts/highlight/styles/sandy.min.css"

extra_head = [
#           '<script async defer data-website-id="fb8e3bc0-187d-4fc7-9d22-d069c4a7f7d4" src="https://umami.sandyuraz.com/umami.js"></script>'
           ]

[project]
exclude = ["present", "scripts", ".saves", ".log"]

[author]
image = "najimi.webp"
name = "sandy"
email = "[at] sandyuraz [dot] com"

[navigation]

[navigation.1]
link = "dossier"
title = "Dossier ğŸ–‹"

[navigation.2]
link = "books"
title = "Bookshelf ğŸ”–"

[navigation.3]
link = "fortunes"
title = "Fortunes ğŸ§§"

[navigation.4]
link = ""
title = "Home ğŸ "
