title = "Sandyâ€™s Website â›©ï¸"
url = "https://sandyuraz.com"

[website]
locale = "en_GB"
color = "#fbebef"
twitter = "@sandyuraz"
styles = ["css/darkness.css"]
tombs = ["blogs", "anime", "arts", "books"]
preview = "preview.jpg"
description_length = 137
roman_footnotes = true
footnote_brackets = false
clickable_images = false

syntax_highlighting = true
syntax_highlighting_languages = "scripts/highlight/languages"
syntax_highlighting_theme = "scripts/highlight/styles/sandy.min.css"

extra_head = [
           # '<script async defer data-website-id="fb8e3bc0-187d-4fc7-9d22-d069c4a7f7d4" src="https://umami.sandyuraz.com/umami.js"></script>'
           # '<script async defer src="/scripts/snowstorm-min.js"></script>'
           ]

[project]
input = ".org"
output = ".html"
exclude = ["present", "scripts", ".saves", ".log"]
vendor_directory = "darkness-stuff/vendored"
preview_directory = "darkness-stuff/previews"

[author]
image = "najimi.webp"
name = "sandy"
name_enable = false
email = "darkness [at] sandyuraz [dot] com"
email_enable = true

[rss]
enable = true
language = "en-us"
description = ""
copyright = "Copyright 2023, Sandy Urazayev"
managing_editor = "sandy@sandyuraz.com (Sandy Urazayev)"
default_author = "Sandy Urazayev"
web_master = "sandy@sandyuraz.com (Sandy Urazayev)"
category = "Blog"
timezone = "America/Chicago"
default_hour = 18

[external]
search_engines = ["bing.com"] #, "naver.com", "Seznam.cz", "yandex.ru", "yep.com"] # none of these work for some reason


[navigation]

[navigation.1]
link = "/dossier"
title = "Dossier ğŸ–‹"

[navigation.2]
link = "/books"
title = "Bookshelf ğŸ”–"

[navigation.3]
link = "/fortunes"
title = "Fortunes ğŸ§§"

[navigation.4]
link = "/fortunes/kk"
title = "K.K.â€™s Fortunes ğŸ¦‹"

[navigation.5]
link = "../"
title = "Go Up â˜ï¸"
hide = "/"
hide_if = "/"

[navigation.6]
link = "/"
title = "Home ğŸ "
hide = "/"
